feat: df-2-doe windows
ladybug-tools/dragonfly-doe2 pull request #12
Opened 2022-01-04 00:00 UTC by TfedUD

2022-01-04 00:01 UTC, TfedUD commented
ah crap I didn't reset the branch correct and all the ole commits are in there

2022-01-04 00:03 UTC, TfedUD commented
hmm idk why that's failing its passing on my machine

2022-01-04 02:01 UTC, mostaphaRoudsari commented
@TfedUD, I reset the branch to master and pushed your changes. Make sure to pull the changes to your local before pushing any new changes. Do NOT try to merge the changes in your branch. There is no changes. Just rest yours.

2022-01-04 02:19 UTC, mostaphaRoudsari requested changes
Hi @TfedUD, See my comments. I think you should make some changes in the implementation before we merge this PR in. That said, this is very close!

2022-01-04 02:19 UTC, mostaphaRoudsari commented on dragonfly_doe2/doe/floor_space.py
> +        return cls(name=nm, x=x, y=y, width=w, height=h)
You don't need a `classmethod` for this one. This is basically the same as the default `__init__`.

2022-01-04 02:19 UTC, mostaphaRoudsari commented on dragonfly_doe2/doe/floor_space.py
> +    location: int
What is location? I don't see it being set in the class method.

2022-01-04 02:19 UTC, mostaphaRoudsari commented on dragonfly_doe2/doe/floor_space.py
> +    window_data: List[Window]
what about windows for a list of windows?

```suggestion
    windows: List[Window]
```

2022-01-04 02:19 UTC, mostaphaRoudsari commented on dragonfly_doe2/doe/floor_space.py
> +    def from_params(cls, name: str, location: int,  rw_paras: RectWind):
Some docstring will be helpful here. I'm still not sure what is `location` supposed to be.

2022-01-04 02:19 UTC, mostaphaRoudsari commented on dragonfly_doe2/doe/floor_space.py
> +                    f'{name}_wndw_{i}', location+1, org[0],
```suggestion
                    f'{name}_wndw_{i}', location + 1, org[0],
```

2022-01-04 02:19 UTC, mostaphaRoudsari commented on dragonfly_doe2/doe/floor_space.py
> +from dragonfly.windowparameter import RectangularWindows as RectWind
Why do we need to shorten the name here. Removing Windows made me really confused as RectWind sound like a single Window to me.

2022-01-04 02:19 UTC, mostaphaRoudsari commented on dragonfly_doe2/doe/floor_space.py
> +        return cls(name=name, location=location+1, window_data=windows)
```suggestion
        return cls(name=name, location=location + 1, window_data=windows)
```

2022-01-04 02:19 UTC, mostaphaRoudsari commented on dragonfly_doe2/doe/floor_space.py
> +            walls.append('\n'.join([wall.to_inp(), window.to_inp()]))
If this is why you wanted to make the implementation object oriented I'm in favor of doing it now. Basically you want to create the windows when creating the walls. That is pretty straight forward and you should only move this code under the Wall class.

2022-01-04 02:23 UTC, TfedUD commented on dragonfly_doe2/doe/floor_space.py
> +            walls.append('\n'.join([wall.to_inp(), window.to_inp()]))
oooo for sure! I'll definitely absorb this into the wall class! that makes a ton of sense and feels more 'right'!

2022-01-04 02:24 UTC, TfedUD commented on dragonfly_doe2/doe/floor_space.py
> +            walls.append('\n'.join([wall.to_inp(), window.to_inp()]))
@ Navy tomorrow so will be able to knock this out while the sun is still coming up!

2022-01-04 12:21 UTC, TfedUD commented
@mostaphaRoudsari did I do the 'pull first' right?
It's not the 'pull with rebase' correct?

2022-01-04 12:26 UTC, TfedUD commented on dragonfly_doe2/doe/floor_space.py
> +        return cls(name=nm, x=x, y=y, width=w, height=h)
sounds good!  this felt a bit verbose; whole-heartedly concur, the choice was a 50/50 "continuity/uniformity vs common sense"  and the Navy makes the option on the left the instinct 😅

2022-01-04 12:29 UTC, TfedUD commented on dragonfly_doe2/doe/floor_space.py
> +    location: int
```python
class WindowSet:
    name: str
    location: int
    window_data: List[Window]

    @classmethod
    def from_params(cls, name: str, location: int,  rw_paras: RectWind):
        origins = [(orig.x, orig.y) for orig in rw_paras.origins]
        widths = rw_paras.widths
        heights = rw_paras.heights

        windows = []
        for i, (org, w, h) in enumerate(zip(origins, widths, heights)):
            windows.append(
                Window(
                    f'{name}_wndw_{i}', location+1, org[0], ######  Arg 2
                    org[1],
                    w, h))
        return cls(name=name, location=location+1, window_data=windows)

    def to_inp(self):
        return '\n'.join([wndw.to_inp() for wndw in self.window_data])

    def __repr__(self):
        return self.to_inp()
```
have location in there to be a part of the 'serialization' of the window objs names to mitigate duplicate name issues

2022-01-06 03:10 UTC, mostaphaRoudsari commented
Hi @TfedUD, you should have used `git reset` to reset to the latest commit. It is again messed up right now. I can try to fix the git history tomorrow morning and then review the changes.

2022-01-06 03:11 UTC, TfedUD commented
@mostaphaRoudsari  DAMNIT lol *bigfacepalm*

2022-01-06 03:42 UTC, mostaphaRoudsari commented
I cleaned it up! Also cleaned up the other new branch on top of this one.
![image](https://user-images.githubusercontent.com/2915573/148324854-1a06e2aa-51ad-43df-8d9b-d1079d846ac7.png)

2022-01-06 15:11 UTC, mostaphaRoudsari approved these changes
LGTM! There are parts that we can clean up later.

I'll merge this in so we can move forward quickly and fix the export for the apertures.

2022-01-06 15:11 UTC, merged